# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Записки об НЛП
tagline:             'Заметки, упражнения и мысли'
description:         'Полезные вещи, которые я узнал и понял за время изучения НЛП.'
url:                 http://konstantin-morenko.ru
baseurl:             ''
paginate:            10
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Константин Моренко
  url:               https://konstantin-morenko.ru
  email:             me@konstantin-morenko.ru

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
theme: jekyll-theme-slate